# Pandas oefeningen: deel 2

In [1]:
import numpy as np
import pandas as pd

np.random.seed(10)

# gegeven: de punten van 10 studenten voor 6 vakken
punten = np.random.randint(7, 20, (10, 6))
print(punten)
studenten = ['otis', 'maeve', 'eric', 'adam', 'aimee', 'ruby', 'ola', 'cal', 'vivienne', 'rahim']

C:\Users\u0092789\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

[[16 11  7  8 18 19]
 [16  7  8 17 15 16]
 [ 7 17 15 13 11 10]
 [ 7 11 18 13 15 18]
 [17  8 15 11  8 10]
 [13 12 10 16 19 13]
 [16 19  8 16 11 18]
 [ 9 13 14 15 18 19]
 [17 15 16  9  7 13]
 [14 15 18  8 14 18]]

## Vraag 1

Maak een pandas DataFrame aan met de gegeven studenten.
Tip: geef via het argument 'columns' een lijst van vakken mee (we zetten de index gelijk aan de lijst met studenten):

In [2]:
df = pd.DataFrame(data=punten, columns=['vak1', 'vak2', 'vak3', 'vak4', 'vak5', 'vak6'])
df.index = studenten
df

          vak1  vak2  vak3  vak4  vak5  vak6
otis        16    11     7     8    18    19
maeve       16     7     8    17    15    16
eric         7    17    15    13    11    10
adam         7    11    18    13    15    18
aimee       17     8    15    11     8    10
ruby        13    12    10    16    19    13
ola         16    19     8    16    11    18
cal          9    13    14    15    18    19
vivienne    17    15    16     9     7    13
rahim       14    15    18     8    14    18

## Vraag 2

Wie is er niet van vak 2 gebuisd?

In [3]:
beste_studenten = df[df.vak2 >= 10]
beste_studenten

          vak1  vak2  vak3  vak4  vak5  vak6
otis        16    11     7     8    18    19
eric         7    17    15    13    11    10
adam         7    11    18    13    15    18
ruby        13    12    10    16    19    13
ola         16    19     8    16    11    18
cal          9    13    14    15    18    19
vivienne    17    15    16     9     7    13
rahim       14    15    18     8    14    18

## Vraag 3

Wie is er voor geen enkel vak gebuisd?

In [4]:
goede_studenten = set(studenten)
for vak in df.columns:
    uitkomst = df[df[vak] < 10]
    goede_studenten = goede_studenten.difference(set(uitkomst.index))

print('Goede studenten:', goede_studenten)

Goede studenten: {'ruby'}

## Vraag 4

Wie is de beste student (heeft de hoogste punten)?

Uitkomst: geef de naam van de student als een string.

Tip: gebruik ofwel `idxmax()` (zoek op op internet) ofwel een for-loop.

Met for-loop:

In [5]:
beste_student = ''
beste_punt = 0
for student, punten in df.iterrows():
    som = punten.sum()
    print(student, som)
    if som > beste_punt:
        beste_punt = som
        beste_student = student
print('Beste student:', beste_student)

otis 79
maeve 79
eric 73
adam 82
aimee 69
ruby 83
ola 88
cal 88
vivienne 77
rahim 87
Beste student: ola

Met `idmax()`:

In [6]:
print('Beste student:', df.sum(axis=1).idxmax())

# alternatief
print('Beste student:', df[df.sum(axis=1) == df.sum(axis=1).max()].index[0])

Beste student: ola
Beste student: ola