# Vraag 1

Gegeven is een Pandas `DataFrame`-object `dataframe_in`. Schrijf code die alle rijen verwijdert waarvan het gemiddelde strikt kleiner is dan de opgegegeven variabele `min_gemiddelde` en geef het resultaat terug als een nieuwe dataframe in variabele `dataframe_out`.

In [1]:
def pandas_oefening(dataframe_in, min_gemiddelde):
    ## LET OP, GEBRUIK 'dataframe_in' en niet 'df'
    print('Originele data:\n', dataframe_in)
    
    # ...

    # stop de uitkomst in de variabele `dataframe_out`
    return dataframe_out

In [2]:
import pandas as pd
import numpy as np

data = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns = ['c1', 'c2', 'c3'])

df_out = pandas_oefening(df, 8)
print('Finale uitkomst:')
df_out

C:\Users\u0092789\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

Originele data:
    c1  c2  c3
0   1   2   3
1   4   5   6
2   7   8   9
0     6
1    15
2    24
dtype: int64
Finale uitkomst:

   c1  c2  c3
1   4   5   6
2   7   8   9

In [3]:
assert np.allclose(df_out.values, [[4, 5, 6], 
                                   [7, 8, 9]])

In [4]:
# verwijder dit NIET
np.random.seed(5)

data = np.random.randint(10, 20, size=(10, 5))
df = pd.DataFrame(data, columns = ['c1', 'c2', 'c3', 'c4', 'c5'])

df_out = pandas_oefening(df, 70)
print('Finale uitkomst:')
df_out

Originele data:
    c1  c2  c3  c4  c5
0  13  16  16  10  19
1  18  14  17  10  10
2  17  11  15  17  10
3  11  14  16  12  19
4  19  19  19  11  12
5  17  10  15  10  10
6  14  14  19  13  12
7  14  16  19  13  13
8  12  11  15  17  14
9  13  11  17  13  11
0    74
1    69
2    70
3    72
4    80
5    62
6    72
7    75
8    69
9    65
dtype: int64
Finale uitkomst:

   c1  c2  c3  c4  c5
0  13  16  16  10  19
2  17  11  15  17  10
3  11  14  16  12  19
4  19  19  19  11  12
6  14  14  19  13  12
7  14  16  19  13  13

In [5]:
assert np.allclose(df_out.values, [[13,16,16,10,19],
 [17,11,15,17,10],
 [11,14,16,12,19],
 [19,19,19,11,12],
 [14,14,19,13,12],
 [14,16,19,13,13]])

# Vraag 2

Gegeven: de dataframe `df_in` uit het bestand `heart_disease_data.csv`. Het bestand bevat informatie over hartpatiënten en bevat kolommen zoals de leeftijd, gender, cholesterol gehalte, maximale hartslag, enz.
Los de volgende vragen hieronder op.

Bron data: https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/

In [6]:
def vind_antwoorden_in_dataset(df_in):
    ## LET OP, GEBRUIK 'df_in' en niet 'df'
    
    #1. aggregeer de numerieke kolommen op basis van de kolommen 'ST_Slope' en 'HeartDisease'
    # via de mediaan
    # stop het resultaat in de variabele `aggregatie` (die je aanmaakt)
    # ...
    print('Aggregatie:\n', aggregatie)
                                                        
    #2. filter de dataframe:
    # De waarden van 'Age' moeten strikt boven de mediaan van de kolom liggen
    # 'MaxHR' moet strikt boven de 170 zijn
    # 'ChestPainType' moet van het type 'NAP' zijn
    # stop dit in de nieuwe variabele `filtered_df`
    # ... 
    print(mediaan)
    # ...
    
    # filter nu `filtered_df` zodat enkel numerieke kolommen behouden blijven
    # en stop dit in `filtered_df2`
    # ...
    
    print('Gefilterede dataframe:\n', filtered_df2)
    
    #3. tel het aantal voorkomens van 'Up' voor de variabele 'ST_Slope' in `filtered_df`
    # houd dit bij als een integer in de variabele `d1`
    # ...
    print('Aantal:', d1)
    
    return aggregatie, filtered_df2, d1

In [7]:
import pandas as pd 
import numpy as np

df = pd.read_csv('heart_disease_data.csv')
a1, a2, a3 = vind_antwoorden_in_dataset(df)

Aggregatie:
                         Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
ST_Slope HeartDisease
Down     0             55.0      130.0        236.5        0.0  147.5     1.45
         1             60.0      125.0        200.0        0.0  127.0     2.00
Flat     0             54.0      130.0        229.0        0.0  146.0     1.00
         1             56.0      135.0        220.0        0.0  124.0     1.20
Up       0             50.0      130.0        226.0        0.0  150.0     0.00
         1             58.0      127.0        192.0        0.0  144.0     0.75
54.0
Gefilterede dataframe:
      Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease
320   59        125            0          1    175      2.6             1
675   57        150          126          1    173      0.2             0
751   67        152          277          0    172      0.0             0
763   58        132          224          0    173      3.2             1
831   63        135          252          0    172      0.0             0
837   57        150          168          0    174      1.6             0
875   58        120          340          0    172      0.0             0
Aantal: 6

In [8]:
assert np.allclose(a1.values, [[ 55.  , 130.  , 236.5 ,   0.  , 147.5 ,   1.45],
       [ 60.  , 125.  , 200.  ,   0.  , 127.  ,   2.  ],
       [ 54.  , 130.  , 229.  ,   0.  , 146.  ,   1.  ],
       [ 56.  , 135.  , 220.  ,   0.  , 124.  ,   1.2 ],
       [ 50.  , 130.  , 226.  ,   0.  , 150.  ,   0.  ],
       [ 58.  , 127.  , 192.  ,   0.  , 144.  ,   0.75]])
assert np.allclose(a2.values, [[5.90e+01, 1.25e+02, 0.00e+00, 1.00e+00, 1.75e+02, 2.60e+00,
        1.00e+00],
       [5.70e+01, 1.50e+02, 1.26e+02, 1.00e+00, 1.73e+02, 2.00e-01,
        0.00e+00],
       [6.70e+01, 1.52e+02, 2.77e+02, 0.00e+00, 1.72e+02, 0.00e+00,
        0.00e+00],
       [5.80e+01, 1.32e+02, 2.24e+02, 0.00e+00, 1.73e+02, 3.20e+00,
        1.00e+00],
       [6.30e+01, 1.35e+02, 2.52e+02, 0.00e+00, 1.72e+02, 0.00e+00,
        0.00e+00],
       [5.70e+01, 1.50e+02, 1.68e+02, 0.00e+00, 1.74e+02, 1.60e+00,
        0.00e+00],
       [5.80e+01, 1.20e+02, 3.40e+02, 0.00e+00, 1.72e+02, 0.00e+00,
        0.00e+00]])
assert a3 == 6

In [9]:
df = pd.read_csv('heart_disease_data.csv')

np.random.seed(100)
selectie = np.random.randint(0, len(df), 100)

a1, a2, a3 = vind_antwoorden_in_dataset(df.iloc[selectie])
assert np.allclose(a1.values, [[ 53.  , 130.  , 233.  ,   1.  , 152.  ,   2.3 ],
       [ 60.  , 136.5 , 198.5 ,   0.  , 121.  ,   2.3 ],
       [ 62.5 , 129.  , 233.  ,   0.  , 125.  ,   0.75],
       [ 55.5 , 139.5 , 230.  ,   0.  , 126.  ,   1.5 ],
       [ 51.5 , 130.  , 245.  ,   0.  , 154.  ,   0.  ],
       [ 58.  , 140.  , 223.  ,   0.  , 162.  ,   0.3 ]])
assert np.allclose(a2.values, [[ 58. , 120. , 340. ,   0. , 172. ,   0. ,   0. ],
       [ 58. , 132. , 224. ,   0. , 173. ,   3.2,   1. ]])
assert a3 == 2

Aggregatie:
                         Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak
ST_Slope HeartDisease
Down     0             53.0      130.0        233.0        1.0  152.0     2.30
         1             60.0      136.5        198.5        0.0  121.0     2.30
Flat     0             62.5      129.0        233.0        0.0  125.0     0.75
         1             55.5      139.5        230.0        0.0  126.0     1.50
Up       0             51.5      130.0        245.0        0.0  154.0     0.00
         1             58.0      140.0        223.0        0.0  162.0     0.30
56.0
Gefilterede dataframe:
      Age  RestingBP  Cholesterol  FastingBS  MaxHR  Oldpeak  HeartDisease
875   58        120          340          0    172      0.0             0
763   58        132          224          0    173      3.2             1
Aantal: 2

# Vraag 3

Los deze vragen op over de Pandas dataframe over panda's. 

- Vraag 1: bereken de gemiddelde lengte van alle panda's met strikt meer dan 2 vlekken.
- Vraag 2: maak een nieuwe kolom 'bmi' aan in `dfv`, uitgewerkt met for-lus of lambda-functie. Het bmi wordt berekend als $\frac{Gewicht}{Lengte^2}$.
- Vraag 3: groepeer de panda's per 'Aantal_Vlekken' en 'Heeft_Staart' en geef het gemiddelde terug voor de numerische kolommen 'Gewicht' en 'Lengte'. Allemaal in die volgorde (zie voorbeelduitkomst).
- Vraag 4: geef een lijst (Python lijst) met daarin al de geluiden van de zwangere panda's.

Voor elke vraag: er wordt in elke vraag een kopij gemaakt `dfv` van de originele dataframe, gebruik deze dataframe. Als je `df` gebruikt gaan jouw verbetering NIET kloppen.

In [10]:
def vraag_1(df_in):
    dfv = df_in.copy()
    
    # ...
    
    return gemiddelde_lengte

In [11]:
def vraag_2(df_in):
    dfv = df_in.copy()
        
    # ...
    return dfv

In [12]:
def vraag_3(df_in):
    dfv = df_in.copy()
    
    # ...
    return gb

In [13]:
def vraag_4(df_in):
    dfv = df_in.copy()
    
    # ...
    return list(df_f)

In [14]:
import numpy as np
import pandas as pd

np.random.seed(42)

aantal = 15
data = {
    'Gewicht': np.random.normal(100, 25, aantal),
    'Leeftijd': np.random.randint(1, 15, aantal),
    'Lengte': np.random.uniform(1.5, 2.0, aantal),
    'Is_Zwanger': np.random.choice([True, False], size=aantal),
    'Aantal_Vlekken': np.random.randint(0, 5, aantal),
    'Geluid': np.random.choice(['Grom', 'Brom', 'Grom', 'Grom', 'Knor'], size=aantal),
    'Heeft_Staart': np.random.choice([True, False], size=aantal)
}
df = pd.DataFrame(data)
df

,Gewicht,Leeftijd,Lengte,Is_Zwanger,Aantal_Vlekken,Geluid,Heeft_Staart
0,112.417854,11,1.840154,False,3,Knor,True
1,96.543392,10,1.725250,False,3,Grom,False
2,116.192213,12,1.506632,False,0,Grom,True
3,138.075746,12,1.971101,False,4,Grom,False
4,94.146166,14,1.781644,False,4,Grom,True
5,94.146576,14,1.692708,False,1,Grom,True
6,139.480320,14,1.507983,False,4,Grom,False
7,119.185868,3,1.615447,False,1,Grom,False
8,88.263140,12,1.620513,True,0,Grom,False
9,113.564001,7,1.841632,True,3,Grom,True
10,88.414558,4,1.804998,False,3,Grom,False
11,88.356756,9,1.916597,False,3,Grom,True
12,106.049057,3,1.586682,False,4,Grom,True
13,52.167994,5,1.695530,False,0,Knor,False
14,56.877054,3,1.591118,False,4,Brom,False

In [15]:
assert np.allclose(vraag_1(df).round(3), 1.757)
assert np.allclose(vraag_2(df)['bmi'].values, [33.1991572 , 32.43535621, 51.1873178 , 35.5385494 , 29.65928823,
       32.85793815, 61.33663868, 45.67088035, 33.61046181, 33.48382731,
       27.13752086, 24.0534817 , 42.12373204, 18.1465063 , 22.46633826])
assert np.allclose(vraag_3(df).values, [[ 70.21556712,   1.65802152],
       [116.19221345,   1.50663248],
       [119.18586823,   1.61544691],
       [ 94.14657608,   1.69270825],
       [ 92.47897508,   1.76512398],
       [104.77953703,   1.86612766],
       [111.477707  ,   1.69006735],
       [100.09761121,   1.68416322]])
assert vraag_4(df) == ['Grom']

# Vraag 4

Gegeven zijn 2 dataframes:
- `machines_df` bevat 3 kolommen: de naam van een machine, de looptijd en omsteltijd.
- `taken_df` bevat 2 kolommen: een taaknaam en een tupel met daarin de namen van de machines die nodig zijn om de taak uit te voeren.

Vervolledig de functie `bereken_totale_doorlooptijd()` die als lambda-functie wordt uitgevoerd over de kolom 'Combinatie' in `taken_df` om een nieuwe kolom 'Totale Doorlooptijd' te maken voor `taken_df`. Het argument `taak_combinatie` is de tupel per rij die moet gebruikt worden, in combinatie met `machine_df` waarin je de totale doorlooptijd (omsteltijd + looptijd van elke machine opgeteld) te berekenen per taak.

In [29]:
import pandas as pd
import numpy as np
import random

random.seed(10)
np.random.seed(10)

def bereken_totale_doorlooptijd(taak_combinatie, machines_df):
    print('Taak combinatie:', taak_combinatie)
    print('Machine_df:\n', machines_df)
    totale_doorlooptijd = 0
    
    for machine in taak_combinatie:
        print('Machine:', machine)
#         print('Info machine:', machines_df[machines_df['Machine'] == machine])
        rij_machine = machines_df[machines_df['Machine'] == machine]
        omstel = rij_machine['Omsteltijd']
        looptijd = rij_machine['Looptijd']
        print(rij_machine)
        print(omstel.values[0], omstel.iloc[0])
        print(looptijd.values[0], looptijd.iloc[0])
        totale_doorlooptijd = omstel.values[0] + looptijd.values[0]
    # overloop machine per taak
        # haal de looptijd/omsteltijd van elke taak per machine op in machines_df
        # update totale doorlooptijd
    # ...
   #     print('Totale doorlooptijd', machine, ':', totale_doorlooptijd)
        
    return totale_doorlooptijd

In [30]:
machines_data = {'Machine': ['A', 'B', 'C'],
                 'Looptijd': [10, 15, 20],
                 'Omsteltijd': [5, 8, 10]}
machines_df = pd.DataFrame(machines_data)

taken_data = {'Taak': ['Taak1', 'Taak2', 'Taak3'],
              'Combinatie': [('A', 'B'), ('B', 'C'), ('A', 'C')]}
taken_df = pd.DataFrame(taken_data)

print(machines_df)
print(taken_df)

taken_df['Totale Doorlooptijd'] = taken_df['Combinatie'].apply(lambda x: bereken_totale_doorlooptijd(x, machines_df))
taken_df

  Machine  Looptijd  Omsteltijd
0       A        10           5
1       B        15           8
2       C        20          10
    Taak Combinatie
0  Taak1     (A, B)
1  Taak2     (B, C)
2  Taak3     (A, C)
Taak combinatie: ('A', 'B')
Machine_df:
   Machine  Looptijd  Omsteltijd
0       A        10           5
1       B        15           8
2       C        20          10
Machine: A
  Machine  Looptijd  Omsteltijd
0       A        10           5
5 5
10 10
Machine: B
  Machine  Looptijd  Omsteltijd
1       B        15           8
8 8
15 15
Taak combinatie: ('B', 'C')
Machine_df:
   Machine  Looptijd  Omsteltijd
0       A        10           5
1       B        15           8
2       C        20          10
Machine: B
  Machine  Looptijd  Omsteltijd
1       B        15           8
8 8
15 15
Machine: C
  Machine  Looptijd  Omsteltijd
2       C        20          10
10 10
20 20
Taak combinatie: ('A', 'C')
Machine_df:
   Machine  Looptijd  Omsteltijd
0       A        10           5
1       B        15           8
2       C        20          10
Machine: A
  Machine  Looptijd  Omsteltijd
0       A        10           5
5 5
10 10
Machine: C
  Machine  Looptijd  Omsteltijd
2       C        20          10
10 10
20 20

    Taak Combinatie  Totale Doorlooptijd
0  Taak1     (A, B)                   23
1  Taak2     (B, C)                   30
2  Taak3     (A, C)                   30

In [18]:
assert np.allclose(taken_df['Totale Doorlooptijd'].values, [38, 53, 45])

In [19]:
aantal_machines = 10
aantal_taken = 5
machines_data = {'Machine': ['machine_' + str(i) for i in range(aantal_machines)],
                 'Looptijd': np.random.randint(10, 20, aantal_machines),
                 'Omsteltijd': np.random.randint(3, 5, aantal_machines)}
machines_df = pd.DataFrame(machines_data)

taken_data = {'Taak': ['taak_' + str(i) for i in range(aantal_taken)],
              'Combinatie': [tuple(random.sample(machines_data['Machine'], 4)) for i in range(aantal_taken)]}
taken_df = pd.DataFrame(taken_data)

print(machines_df)
print(taken_df)

taken_df['Totale Doorlooptijd'] = taken_df['Combinatie'].apply(lambda x: bereken_totale_doorlooptijd(x, machines_df))
taken_df

     Machine  Looptijd  Omsteltijd
0  machine_0        19           3
1  machine_1        14           3
2  machine_2        10           3
3  machine_3        11           3
4  machine_4        19           4
5  machine_5        10           3
6  machine_6        11           3
7  machine_7        18           4
8  machine_8        19           4
9  machine_9        10           3
     Taak                                    Combinatie
0  taak_0  (machine_9, machine_0, machine_6, machine_3)
1  taak_1  (machine_9, machine_0, machine_3, machine_7)
2  taak_2  (machine_7, machine_4, machine_2, machine_0)
3  taak_3  (machine_8, machine_7, machine_5, machine_0)
4  taak_4  (machine_3, machine_5, machine_0, machine_9)
Taak combinatie: ('machine_9', 'machine_0', 'machine_6', 'machine_3')
Totale doorlooptijd machine_9 : 13
Totale doorlooptijd machine_0 : 35
Totale doorlooptijd machine_6 : 49
Totale doorlooptijd machine_3 : 63
Taak combinatie: ('machine_9', 'machine_0', 'machine_3', 'machine_7')
Totale doorlooptijd machine_9 : 13
Totale doorlooptijd machine_0 : 35
Totale doorlooptijd machine_3 : 49
Totale doorlooptijd machine_7 : 71
Taak combinatie: ('machine_7', 'machine_4', 'machine_2', 'machine_0')
Totale doorlooptijd machine_7 : 22
Totale doorlooptijd machine_4 : 45
Totale doorlooptijd machine_2 : 58
Totale doorlooptijd machine_0 : 80
Taak combinatie: ('machine_8', 'machine_7', 'machine_5', 'machine_0')
Totale doorlooptijd machine_8 : 23
Totale doorlooptijd machine_7 : 45
Totale doorlooptijd machine_5 : 58
Totale doorlooptijd machine_0 : 80
Taak combinatie: ('machine_3', 'machine_5', 'machine_0', 'machine_9')
Totale doorlooptijd machine_3 : 14
Totale doorlooptijd machine_5 : 27
Totale doorlooptijd machine_0 : 49
Totale doorlooptijd machine_9 : 62

     Taak                                    Combinatie  Totale Doorlooptijd
0  taak_0  (machine_9, machine_0, machine_6, machine_3)                   63
1  taak_1  (machine_9, machine_0, machine_3, machine_7)                   71
2  taak_2  (machine_7, machine_4, machine_2, machine_0)                   80
3  taak_3  (machine_8, machine_7, machine_5, machine_0)                   80
4  taak_4  (machine_3, machine_5, machine_0, machine_9)                   62

In [20]:
assert np.allclose(taken_df['Totale Doorlooptijd'].values, [63, 71, 80, 80, 62])