# 1B.2 Korte Pandas oefeningen

## 1. Data over verkeersongevallen

In deze notebook gebruiken we de open data omtrent het aantal ongevallen op de weg in 2020.
De metadata is beschikbaar in TF_ACCIDENTS metadata.xlxs

Bron: https://statbel.fgov.be/en/open-data/road-accidents-2020

Eerst importeren we pandas:

In [1]:
import pandas as pd

### Vraag 0: 

Lees bestand 'TF_ACCIDENTS_2020.csv' in

In [2]:
df = pd.read_csv('TF_ACCIDENTS_2020.csv')
df.head()

,DT_DAY,TX_DAY_OF_WEEK_DESCR_NL,TX_BUILD_UP_AREA_DESCR_NL,TX_COLL_TYPE_DESCR_NL,TX_LIGHT_COND_DESCR_NL,TX_ROAD_TYPE_DESCR_NL,TX_MUNTY_DESCR_NL,TX_PROV_DESCR_NL,MS_ACCT,MS_ACCT_WITH_DEAD,MS_ACCT_WITH_DEAD_30_DAYS,MS_ACCT_WITH_MORY_INJ,MS_ACCT_WITH_SERLY_INJ,MS_ACCT_WITH_SLY_INJ
0,28-Nov-20,zaterdag,Buiten bebouwde kom,Langs achteren (of naast elkaar),Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,0,0,0,0,1
1,24-Sep-20,donderdag,Binnen bebouwde kom,Langs achteren (of naast elkaar),Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,0,0,0,0,1
2,14-Dec-20,maandag,Buiten bebouwde kom,Langs achteren (of naast elkaar),Bij klaarlichte dag,Autosnelweg,Aartselaar,Provincie Antwerpen,1,0,0,0,0,1
3,18-Nov-20,woensdag,Binnen bebouwde kom,Langs opzij,"Nacht, ontstoken openbare verlichting","Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,0,0,0,1,0
4,17-Sep-20,donderdag,Binnen bebouwde kom,Langs opzij,Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,0,0,0,0,1

### Vraag 1: 

Hoeveel rijen zitten er in de dataset?

In [3]:
lengte = len(df)
print('Aantal rijen:', lengte)

Aantal rijen: 30102

### Vraag 2a:

Geef enkel de data van kolommen 'TX_BUILD_UP_AREA_DESCR_NL' en 'TX_LIGHT_COND_DESCR_NL' in een nieuwe dataframe.

In [11]:
df_filt = df[['TX_BUILD_UP_AREA_DESCR_NL', 'TX_LIGHT_COND_DESCR_NL']]
df_filt

      TX_BUILD_UP_AREA_DESCR_NL                 TX_LIGHT_COND_DESCR_NL
0           Buiten bebouwde kom                    Bij klaarlichte dag
1           Binnen bebouwde kom                    Bij klaarlichte dag
2           Buiten bebouwde kom                    Bij klaarlichte dag
3           Binnen bebouwde kom  Nacht, ontstoken openbare verlichting
4           Binnen bebouwde kom                    Bij klaarlichte dag
...                         ...                                    ...
30097       Buiten bebouwde kom                    Bij klaarlichte dag
30098       Buiten bebouwde kom                    Bij klaarlichte dag
30099       Binnen bebouwde kom                    Bij klaarlichte dag
30100       Buiten bebouwde kom                    Bij klaarlichte dag
30101       Buiten bebouwde kom                    Bij klaarlichte dag

[30102 rows x 2 columns]

### Vraag 2b: 

Geef de 10 laatste rijen van kolommen 'TX_BUILD_UP_AREA_DESCR_NL' en 'TX_LIGHT_COND_DESCR_NL' in een nieuwe dataframe.

Met `iloc()`:

In [4]:
df_filt = df[['TX_BUILD_UP_AREA_DESCR_NL', 'TX_LIGHT_COND_DESCR_NL']].iloc[-10:]
df_filt

      TX_BUILD_UP_AREA_DESCR_NL TX_LIGHT_COND_DESCR_NL
30092       Buiten bebouwde kom    Bij klaarlichte dag
30093       Binnen bebouwde kom    Bij klaarlichte dag
30094       Buiten bebouwde kom    Bij klaarlichte dag
30095       Buiten bebouwde kom    Bij klaarlichte dag
30096       Buiten bebouwde kom    Bij klaarlichte dag
30097       Buiten bebouwde kom    Bij klaarlichte dag
30098       Buiten bebouwde kom    Bij klaarlichte dag
30099       Binnen bebouwde kom    Bij klaarlichte dag
30100       Buiten bebouwde kom    Bij klaarlichte dag
30101       Buiten bebouwde kom    Bij klaarlichte dag

Met `tail()`:

In [5]:
df_filt = df[['TX_BUILD_UP_AREA_DESCR_NL', 'TX_LIGHT_COND_DESCR_NL']].tail(10)
df_filt

      TX_BUILD_UP_AREA_DESCR_NL TX_LIGHT_COND_DESCR_NL
30092       Buiten bebouwde kom    Bij klaarlichte dag
30093       Binnen bebouwde kom    Bij klaarlichte dag
30094       Buiten bebouwde kom    Bij klaarlichte dag
30095       Buiten bebouwde kom    Bij klaarlichte dag
30096       Buiten bebouwde kom    Bij klaarlichte dag
30097       Buiten bebouwde kom    Bij klaarlichte dag
30098       Buiten bebouwde kom    Bij klaarlichte dag
30099       Binnen bebouwde kom    Bij klaarlichte dag
30100       Buiten bebouwde kom    Bij klaarlichte dag
30101       Buiten bebouwde kom    Bij klaarlichte dag

### Vraag 3: 

Hoeveel kolommen zitten er in de dataset?

In [6]:
aantal_kolommen = len(df.columns)
print('Aantal kolommen:', aantal_kolommen)

Aantal kolommen: 14

### Vraag 4: 

Geef het gemiddelde van de numerieke variabelen per type crash ('TX_COLL_TYPE_DESCR_NL') en per weekdag ('TX_DAY_OF_WEEK_DESCR_NL')

In [7]:
per_dag = df.groupby(['TX_COLL_TYPE_DESCR_NL', 'TX_DAY_OF_WEEK_DESCR_NL']).mean()
per_dag

                                                            MS_ACCT  \
TX_COLL_TYPE_DESCR_NL             TX_DAY_OF_WEEK_DESCR_NL
Eén bestuurder, geen hindernis    dinsdag                  1.003984
                                  donderdag                1.000000
                                  maandag                  1.000000
                                  vrijdag                  1.000000
                                  woensdag                 1.000000
...                                                             ...
Tegen een hindernis op de rijbaan maandag                  1.000000
                                  vrijdag                  1.000000
                                  woensdag                 1.009804
                                  zaterdag                 1.020619
                                  zondag                   1.000000

                                                           MS_ACCT_WITH_DEAD  \
TX_COLL_TYPE_DESCR_NL             TX_DAY_OF_WEEK_DESCR_NL
Eén bestuurder, geen hindernis    dinsdag                           0.003984
                                  donderdag                         0.010033
                                  maandag                           0.007407
                                  vrijdag                           0.000000
                                  woensdag                          0.007326
...                                                                      ...
Tegen een hindernis op de rijbaan maandag                           0.011236
                                  vrijdag                           0.012048
                                  woensdag                          0.000000
                                  zaterdag                          0.010309
                                  zondag                            0.018868

                                                           MS_ACCT_WITH_DEAD_30_DAYS  \
TX_COLL_TYPE_DESCR_NL             TX_DAY_OF_WEEK_DESCR_NL
Eén bestuurder, geen hindernis    dinsdag                                   0.015936
                                  donderdag                                 0.013378
                                  maandag                                   0.014815
                                  vrijdag                                   0.007092
                                  woensdag                                  0.010989
...                                                                              ...
Tegen een hindernis op de rijbaan maandag                                   0.022472
                                  vrijdag                                   0.012048
                                  woensdag                                  0.000000
                                  zaterdag                                  0.020619
                                  zondag                                    0.018868

                                                           MS_ACCT_WITH_MORY_INJ  \
TX_COLL_TYPE_DESCR_NL             TX_DAY_OF_WEEK_DESCR_NL
Eén bestuurder, geen hindernis    dinsdag                               0.011952
                                  donderdag                             0.003344
                                  maandag                               0.007407
                                  vrijdag                               0.007092
                                  woensdag                              0.003663
...                                                                          ...
Tegen een hindernis op de rijbaan maandag                               0.011236
                                  vrijdag                               0.000000
                                  woensdag                              0.000000
                                  zaterdag                              0.010309
                                  zondag                                0.000000

                                                           MS_ACCT_WITH_SERLY_INJ  \
TX_COLL_TYPE_DESCR_NL             TX_DAY_OF_WEEK_DESCR_NL
Eén bestuurder, geen hindernis    dinsdag                                0.119522
                                  donderdag                              0.137124
                                  maandag                                0.096296
                                  vrijdag                                0.109929
                                  woensdag                               0.117216
...                                                                           ...
Tegen een hindernis op de rijbaan maandag                                0.089888
                                  vrijdag                                0.084337
                                  woensdag                               0.127451
                                  zaterdag                               0.134021
                                  zondag                                 0.047170

                                                           MS_ACCT_WITH_SLY_INJ
TX_COLL_TYPE_DESCR_NL             TX_DAY_OF_WEEK_DESCR_NL
Eén bestuurder, geen hindernis    dinsdag                              0.868526
                                  donderdag                            0.849498
                                  maandag                              0.888889
                                  vrijdag                              0.882979
                                  woensdag                             0.871795
...                                                                         ...
Tegen een hindernis op de rijbaan maandag                              0.887640
                                  vrijdag                              0.903614
                                  woensdag                             0.882353
                                  zaterdag                             0.865979
                                  zondag                               0.933962

[63 rows x 6 columns]

Houd nu enkel het aantal ongevallen ('MS_ACCT') bij uit `per_dag`:

In [8]:
per_dag['MS_ACCT']

TX_COLL_TYPE_DESCR_NL              TX_DAY_OF_WEEK_DESCR_NL
Eén bestuurder, geen hindernis     dinsdag                    1.003984
                                   donderdag                  1.000000
                                   maandag                    1.000000
                                   vrijdag                    1.000000
                                   woensdag                   1.000000
                                                                ...
Tegen een hindernis op de rijbaan  maandag                    1.000000
                                   vrijdag                    1.000000
                                   woensdag                   1.009804
                                   zaterdag                   1.020619
                                   zondag                     1.000000
Name: MS_ACCT, Length: 63, dtype: float64

### Vraag 5a:

Filter op het type crash ('TX_BUILD_UP_AREA_DESCR_NL') voor crashes buiten de bebouwde kom (waarde 'Buiten bebouwde kom'):

In [13]:
buiten_bebouwde_kom = df[df['TX_BUILD_UP_AREA_DESCR_NL'] == 'Buiten bebouwde kom']
buiten_bebouwde_kom

,DT_DAY,TX_DAY_OF_WEEK_DESCR_NL,TX_BUILD_UP_AREA_DESCR_NL,TX_COLL_TYPE_DESCR_NL,TX_LIGHT_COND_DESCR_NL,TX_ROAD_TYPE_DESCR_NL,TX_MUNTY_DESCR_NL,TX_PROV_DESCR_NL,MS_ACCT,MS_ACCT_WITH_DEAD,MS_ACCT_WITH_DEAD_30_DAYS,MS_ACCT_WITH_MORY_INJ,MS_ACCT_WITH_SERLY_INJ,MS_ACCT_WITH_SLY_INJ
0,28-Nov-20,zaterdag,Buiten bebouwde kom,Langs achteren (of naast elkaar),Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,0,0,0,0,1
2,14-Dec-20,maandag,Buiten bebouwde kom,Langs achteren (of naast elkaar),Bij klaarlichte dag,Autosnelweg,Aartselaar,Provincie Antwerpen,1,0,0,0,0,1
5,27-Jul-20,maandag,Buiten bebouwde kom,Frontale botsing (of bij het kruisen),Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,0,0,0,0,1
6,16-Oct-20,vrijdag,Buiten bebouwde kom,Langs achteren (of naast elkaar),Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,0,0,0,1,0
10,31-Jul-20,vrijdag,Buiten bebouwde kom,Langs opzij,Dageraad - schemering,"Gewestweg, provincieweg of gemeenteweg",Aartselaar,Provincie Antwerpen,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30096,05-Aug-20,woensdag,Buiten bebouwde kom,Langs opzij,Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Pelt,Provincie Limburg,1,0,0,0,0,1
30097,18-Sep-20,vrijdag,Buiten bebouwde kom,Langs opzij,Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Pelt,Provincie Limburg,1,0,0,0,0,1
30098,05-Aug-20,woensdag,Buiten bebouwde kom,Frontale botsing (of bij het kruisen),Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Pelt,Provincie Limburg,1,0,0,0,0,1
30100,11-Jul-20,zaterdag,Buiten bebouwde kom,Langs opzij,Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Pelt,Provincie Limburg,1,0,0,0,0,1
30101,02-Aug-20,zondag,Buiten bebouwde kom,Niet beschikbaar,Bij klaarlichte dag,"Gewestweg, provincieweg of gemeenteweg",Pelt,Provincie Limburg,1,0,0,0,0,1

### Vraag 5b: 

Geef de absolute voorkomens van het type crash ('TX_BUILD_UP_AREA_DESCR_NL') voor crashes buiten de bebouwde kom (waarde 'Buiten bebouwde kom'):

In [14]:
aantal_buiten_bebouwde_kom = df[df['TX_BUILD_UP_AREA_DESCR_NL'] == 'Buiten bebouwde kom']
aantal_buiten_bebouwde_kom['TX_COLL_TYPE_DESCR_NL'].value_counts()

Langs opzij                               2725
Tegen een hindernis buiten de rijbaan     2187
Langs achteren (of naast elkaar)          1776
Niet beschikbaar                          1605
Eén bestuurder, geen hindernis             886
Frontale botsing (of bij het kruisen)      787
Kettingbotsing (4 bestuurders of meer)     521
Met een voetganger                         301
Tegen een hindernis op de rijbaan          268
Name: TX_COLL_TYPE_DESCR_NL, dtype: int64

### Vraag 6: 

Geef het aantal lijnen waarop er meer dan 1 ongeval werd geregistreerd

In [10]:
aantal_lijnen = len(df[df['MS_ACCT'] > 1])
print('Aantal lijnen met meer dan 1 ongeval:', aantal_lijnen)

Aantal lijnen met meer dan 1 ongeval: 126

## 2. Studentenscores

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(10)

# gegeven: de punten van 10 studenten voor 6 vakken
punten = np.random.randint(7, 20, (10, 6))
print(punten)
studenten = ['otis', 'maeve', 'eric', 'adam', 'aimee', 'ruby', 'ola', 'cal', 'vivienne', 'rahim']

C:\Users\u0092789\AppData\Local\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

[[16 11  7  8 18 19]
 [16  7  8 17 15 16]
 [ 7 17 15 13 11 10]
 [ 7 11 18 13 15 18]
 [17  8 15 11  8 10]
 [13 12 10 16 19 13]
 [16 19  8 16 11 18]
 [ 9 13 14 15 18 19]
 [17 15 16  9  7 13]
 [14 15 18  8 14 18]]

### Vraag 1

Maak een pandas DataFrame aan met de gegeven studenten.
Tip: geef via het argument 'columns' een lijst van vakken mee (we zetten de index gelijk aan de lijst met studenten):

In [ ]:
df = pd.DataFrame(data=punten, columns=['vak1', 'vak2', 'vak3', 'vak4', 'vak5', 'vak6'])
df.index = studenten
df

          vak1  vak2  vak3  vak4  vak5  vak6
otis        16    11     7     8    18    19
maeve       16     7     8    17    15    16
eric         7    17    15    13    11    10
adam         7    11    18    13    15    18
aimee       17     8    15    11     8    10
ruby        13    12    10    16    19    13
ola         16    19     8    16    11    18
cal          9    13    14    15    18    19
vivienne    17    15    16     9     7    13
rahim       14    15    18     8    14    18

### Vraag 2

Wie is er niet van vak 2 gebuisd?

In [ ]:
beste_studenten = df[df.vak2 >= 10]
beste_studenten

          vak1  vak2  vak3  vak4  vak5  vak6
otis        16    11     7     8    18    19
eric         7    17    15    13    11    10
adam         7    11    18    13    15    18
ruby        13    12    10    16    19    13
ola         16    19     8    16    11    18
cal          9    13    14    15    18    19
vivienne    17    15    16     9     7    13
rahim       14    15    18     8    14    18

### Vraag 3

Wie is er voor geen enkel vak gebuisd?

In [ ]:
goede_studenten = set(studenten)
for vak in df.columns:
    uitkomst = df[df[vak] < 10]
    goede_studenten = goede_studenten.difference(set(uitkomst.index))

print('Goede studenten:', goede_studenten)

Goede studenten: {'ruby'}

### Vraag 4

Wie is de beste student (heeft de hoogste punten)?

Uitkomst: geef de naam van de student als een string.

Tip: gebruik ofwel `idxmax()` (zoek op op internet) ofwel een for-loop.

Met for-loop:

In [ ]:
beste_student = ''
beste_punt = 0
for student, punten in df.iterrows():
    som = punten.sum()
    print(student, som)
    if som > beste_punt:
        beste_punt = som
        beste_student = student
print('Beste student:', beste_student)

otis 79
maeve 79
eric 73
adam 82
aimee 69
ruby 83
ola 88
cal 88
vivienne 77
rahim 87
Beste student: ola

Met `idmax()`:

In [ ]:
print('Beste student:', df.sum(axis=1).idxmax())

# alternatief
print('Beste student:', df[df.sum(axis=1) == df.sum(axis=1).max()].index[0])

Beste student: ola
Beste student: ola