# 1B.2 Pandas

Pandas is een van de meestgebruikte dataopslag pakketten beschikbaar voor Python. Het vormt een schil van metadata (kolommen, kolomtypes, etc.) rond rauwe data opgeslagen in NumPy matrices en laat het toe die makkelijk te bevragen (met SQL-achtige methodes) en te bewerken.
Er worden veelal 2 objecten gebruikt om dit te bewerkstelligen: de `Series` en de `DataFrame`. De eerste wordt gebruikt om een enkele kolom te vatten met diens data en datatype. Over een enkele kolom kunnen ook statistieken worden berekend zoals `sum()` of `min()`. Een `DataFrame` daarentegen zorgt voor een volledige tabulaire representatie en is een verzameling van verschillende `Series`-objecten aan elkaar. Beiden maken uitgebreid gebruik van een index zoals hieronder te merken. Standaard worden de rijnummers meegenomen, maar soms worden deze overschreven, bv. met een klanten ID of zelfs een datum.

We importeren Pandas als `pd`:

In [1]:
import pandas as pd
import numpy as np

## Series

De `Series` vat dus een enkele kolom (of vlak gezien, een rij). We kunnen ze aanmaken dmv bv. een lijst zoals hieronder:

In [2]:
een_lijst = ['robin', 'ted', 'barney', 'lilly', 'marshall']
een_reeks = pd.Series(een_lijst)
print(een_reeks)

0       robin
1         ted
2      barney
3       lilly
4    marshall
dtype: object

Hieronder is te zien dat we dus een `Series` object hebben aangemaakt. We kunnen de rauwe datawaarden (een NumPy array) opvragen met de methode `values`:

In [3]:
print('De reeks is van het type:', type(een_reeks))
print('De rauwe waarden:', een_reeks.values)
print('De waarden zijn van het type `ndarray` uit NumPy:', type(een_reeks.values))

De reeks is van het type: <class 'pandas.core.series.Series'>
De rauwe waarden: ['robin' 'ted' 'barney' 'lilly' 'marshall']
De waarden zijn van het type `ndarray` uit NumPy: <class 'numpy.ndarray'>

Pandas zal automatisch proberen om het datatype te herkennen. Hierboven gaven we strings mee die werden ondergebracht onder het type 'object' wat staat voor niet-geordende categorische waarden. Hieronder geven we nummers mee die automatisch herkend worden als integer uitgedrukt in 64 bits (`int64`):

In [4]:
een_andere_lijst = [10, 20, 30, 40, 50, 50, 50]
een_andere_reeks = pd.Series(een_andere_lijst)
print('De andere reeks:\n', een_andere_reeks)

De andere reeks:
 0    10
1    20
2    30
3    40
4    50
5    50
6    50
dtype: int64

Pandas kan ook goed met lege cellen om (die worden bijgehouden als `np.nan` constanten). Zo zullen ze niet meegenomen worden in functies zoals `min()` of `mean()`:

In [5]:
een_andere_lijst = [10, 20, 30, 40, 50, 50, 50, np.nan]
een_andere_reeks = pd.Series(een_andere_lijst)
print('NumPy methodes zijn mogelijk (min):', een_andere_reeks.min())
print('NumPy methodes zijn mogelijk (gem.):', een_andere_reeks.mean())

NumPy methodes zijn mogelijk (min): 10.0
NumPy methodes zijn mogelijk (gem.): 35.714285714285715

Lege cellen tellen mee voor `len()`, maar niet voor `value_counts()` - een handige functie om het aantal voorkomens van (categorische/discrete) variabelen op te vragen als dan niet met `normalize` als argument om de relatieve frequentie te verkrijgen - of `count()`:

In [6]:
print('Aantal elementen:', len(een_andere_reeks))
print('Aantal voorkomens:\n', een_andere_reeks.value_counts())
print('Proportioneel voorkomen:\n', een_andere_reeks.value_counts(normalize=True))
print('Aantal niet-lege cellen:', een_andere_reeks.count())

Aantal elementen: 8
Aantal voorkomens:
 50.0    3
10.0    1
20.0    1
30.0    1
40.0    1
Name: count, dtype: int64
Proportioneel voorkomen:
 50.0    0.428571
10.0    0.142857
20.0    0.142857
30.0    0.142857
40.0    0.142857
Name: proportion, dtype: float64
Aantal niet-lege cellen: 7

We kunnen ook de lijst indexering van Python blijven gebruiken op `Series`:

In [7]:
print('Eerste 2 elementen:\n', een_andere_reeks[:2])

Eerste 2 elementen:
 0    10.0
1    20.0
dtype: float64

Wat ook werkt is de `iloc()` functie voor index-localisatie. `DataFrame` objecten kunnen niet met de standaard-indexering gebruikt worden en moeten altijd met `iloc()` gebruikt worden.

In [8]:
print('Eerste 2 elementen met iloc:\n', een_andere_reeks.iloc[:2])

Eerste 2 elementen met iloc:
 0    10.0
1    20.0
dtype: float64

Lambda-functies werken ook op `Series`, zoals hieronder geïllustreerd:

In [9]:
print('Lambda functies werken ook:\n', een_andere_reeks.apply(lambda x: x**2))

Lambda functies werken ook:
 0     100.0
1     400.0
2     900.0
3    1600.0
4    2500.0
5    2500.0
6    2500.0
7       NaN
dtype: float64

## DataFrame

Een `DataFrame` zal dus meerdere `Series` aan elkaar rijgen in een tabel.

### Aanmaken van een DataFrame

Een `DataFrame` kan aangemaakt worden uit verschillende (even lange) lijsten die de aparte kolommen voorstellen. Kolommen moeten natuurlijk wel geïdentificeerd kunnen worden. Ofwel geven we een dictionary mee waarin de lijsten de waarden zijn en de kolomnamen de sleutels, ofwel geven we de lijsten mee in een lijst en geven we de kolomnamen mee als een aparte lijst aan de `DataFrame` functie onder het argument `columns`. Jupyter notebooks zijn ook voorzien op Pandas dataframes, zou moet de `print()` functie niet gebruikt worden om ze gestructureerd te visualiseren:

In [10]:
namen_lijst = ['robin', 'ted', 'barney', 'lilly', 'marshall']
aantal_lijst = [10, 20, 30, 40, 50]

personages_dict = {'personages': namen_lijst, 'aantal': aantal_lijst}
df = pd.DataFrame(personages_dict)
df

  personages  aantal
0      robin      10
1        ted      20
2     barney      30
3      lilly      40
4   marshall      50

In [11]:
andere_data = [['johannes', 10], ['giovanni', 2], ['john', 3], ['jan', 30]]
df_2 = pd.DataFrame(andere_data, columns=['naam', 'aantal'])
df_2

       naam  aantal
0  johannes      10
1  giovanni       2
2      john       3
3       jan      30

De index kan als volgt worden opgevraagd:

In [12]:
df_2.index

RangeIndex(start=0, stop=4, step=1)

De index is van het type `Index` en heeft ook een NumPy array als waarden:

In [13]:
print(type(df_2.index))
print(type(df_2.index.values))
df_2.index.values

<class 'pandas.core.indexes.range.RangeIndex'>
<class 'numpy.ndarray'>

array([0, 1, 2, 3])

We kunnen de index ook aanpassen, bv. door de namen te gebruiken als index:

In [14]:
df_2.index = df_2['naam']
df_2

              naam  aantal
naam
johannes  johannes      10
giovanni  giovanni       2
john          john       3
jan            jan      30

`iloc()` werkt ook nog:

In [15]:
df_2.iloc[:2]

              naam  aantal
naam
johannes  johannes      10
giovanni  giovanni       2

We kunnen bij een `DataFrame` ook `loc()` gebruiken door elementen van de index op te vragen:

In [16]:
df_2.loc[['johannes', 'jan']]

              naam  aantal
naam
johannes  johannes      10
jan            jan      30